/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package provis_4.praktek2;

/**
 *
 * @author binta
 */
public class Praktek2Window extends javax.swing.JFrame {

    /**
     * Creates new form Praktek2Window
     */
    double nilai_a;
    double nilai_b;
    boolean hasil;
    
    public Praktek2Window() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfa = new javax.swing.JTextField();
        tfb = new javax.swing.JTextField();
        samadengan = new javax.swing.JButton();
        tidaksama = new javax.swing.JButton();
        besardari = new javax.swing.JButton();
        kurangdari = new javax.swing.JButton();
        besarsama = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tfHasil = new javax.swing.JTextField();
        kurangsama = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Program Operator Pembanding");

        jLabel2.setText("Nilai A");

        jLabel3.setText("Nilai B");

        tfa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfaActionPerformed(evt);
            }
        });

        samadengan.setText("==");
        samadengan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                samadenganActionPerformed(evt);
            }
        });

        tidaksama.setText("!=");
        tidaksama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidaksamaActionPerformed(evt);
            }
        });

        besardari.setText(">");
        besardari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                besardariActionPerformed(evt);
            }
        });

        kurangdari.setText("<");
        kurangdari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kurangdariActionPerformed(evt);
            }
        });

        besarsama.setText(">=");
        besarsama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                besarsamaActionPerformed(evt);
            }
        });

        jLabel4.setText("Hasil");

        tfHasil.setEditable(false);

        kurangsama.setText("<=");
        kurangsama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kurangsamaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfa)
                                    .addComponent(tfb, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(tfHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(samadengan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tidaksama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(besardari, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kurangdari, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(besarsama, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kurangsama)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(samadengan)
                    .addComponent(tidaksama)
                    .addComponent(besardari)
                    .addComponent(besarsama)
                    .addComponent(kurangdari)
                    .addComponent(kurangsama))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfHasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfaActionPerformed

    private void samadenganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_samadenganActionPerformed
        nilai_a=Double.valueOf(tfa.getText());
        nilai_b=Double.valueOf(tfb.getText());
        hasil = nilai_a == nilai_b;
        tfHasil.setText(String.valueOf(hasil));
    }//GEN-LAST:event_samadenganActionPerformed

    private void besardariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_besardariActionPerformed
        nilai_a=Double.valueOf(tfa.getText());
        nilai_b=Double.valueOf(tfb.getText());
        hasil = nilai_a > nilai_b;
        tfHasil.setText(String.valueOf(hasil));
    }//GEN-LAST:event_besardariActionPerformed

    private void kurangdariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kurangdariActionPerformed
        nilai_a=Double.valueOf(tfa.getText());
        nilai_b=Double.valueOf(tfb.getText());
        hasil = nilai_a < nilai_b;
        tfHasil.setText(String.valueOf(hasil));
    }//GEN-LAST:event_kurangdariActionPerformed

    private void besarsamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_besarsamaActionPerformed
        nilai_a=Double.valueOf(tfa.getText());
        nilai_b=Double.valueOf(tfb.getText());
        hasil = nilai_a >= nilai_b;
        tfHasil.setText(String.valueOf(hasil));
    }//GEN-LAST:event_besarsamaActionPerformed

    private void kurangsamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kurangsamaActionPerformed
        nilai_a=Double.valueOf(tfa.getText());
        nilai_b=Double.valueOf(tfb.getText());
        hasil = nilai_a <= nilai_b;
        tfHasil.setText(String.valueOf(hasil));

    }//GEN-LAST:event_kurangsamaActionPerformed

    private void tidaksamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidaksamaActionPerformed
        nilai_a=Double.valueOf(tfa.getText());
        nilai_b=Double.valueOf(tfb.getText());
        hasil = nilai_a != nilai_b;
        tfHasil.setText(String.valueOf(hasil));

    }//GEN-LAST:event_tidaksamaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Praktek2Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Praktek2Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Praktek2Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Praktek2Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Praktek2Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton besardari;
    private javax.swing.JButton besarsama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton kurangdari;
    private javax.swing.JButton kurangsama;
    private javax.swing.JButton samadengan;
    private javax.swing.JTextField tfHasil;
    private javax.swing.JTextField tfa;
    private javax.swing.JTextField tfb;
    private javax.swing.JButton tidaksama;
    // End of variables declaration//GEN-END:variables
}
